# need 4 gpus

project: coconut
save_path: results/gsm
name: gsm-icot-2

only_eval: False

coconut: False
cot: False
no_thoughts: False
no_cot: True

c_thought: 2
epochs_per_stage: 5
max_latent_stage: 3
pad_latent_to_max: True

save_only_improve: True
save_stage_on_improve: True
uniform_prob: 0.0
model_id: "Qwen/Qwen2.5-1.5B"
load_model_path: None
seed: 0
resume: 0
bf16: True # False
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: True
batch_size_training: 24
debug: False
gradient_accumulation_steps: 1
num_epochs: 60
lr: !!float "1e-4"
weight_decay: 0.01